In [9]:
import pandas as pd
import nltk
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from textblob import TextBlob
from collections import Counter

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

**Collecting restaurant review data**

In [10]:
reviews = [
    "The pizza was delicious and delivery was very fast.",
    "Food arrived cold and the packaging was damaged.",
    "Excellent customer service and tasty food.",
    "Delivery was late and food quality was poor.",
    "The burger was amazing and fresh.",
    "Very expensive compared to the quantity served.",
    "Packaging was good but delivery was slow.",
    "Loved the pasta and friendly staff.",
    "Food was average but customer support was helpful.",
    "Terrible experience, wrong order delivered."
]

df = pd.DataFrame(reviews, columns=['Review'])

df.head()

                                              Review
0  The pizza was delicious and delivery was very ...
1   Food arrived cold and the packaging was damaged.
2         Excellent customer service and tasty food.
3       Delivery was late and food quality was poor.
4                  The burger was amazing and fresh.

**Preprocess customer feedback text**

In [11]:
stop_words = set(stopwords.words('english'))

def preprocess(text):

    text = text.lower()

    text = text.translate(str.maketrans('', '', string.punctuation))

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in stop_words]

    return " ".join(tokens)

df["Clean_Review"] = df["Review"].apply(preprocess)

df

,Review,Clean_Review
0,The pizza was delicious and delivery was very ...,pizza delicious delivery fast
1,Food arrived cold and the packaging was damaged.,food arrived cold packaging damaged
2,Excellent customer service and tasty food.,excellent customer service tasty food
3,Delivery was late and food quality was poor.,delivery late food quality poor
4,The burger was amazing and fresh.,burger amazing fresh
5,Very expensive compared to the quantity served.,expensive compared quantity served
6,Packaging was good but delivery was slow.,packaging good delivery slow
7,Loved the pasta and friendly staff.,loved pasta friendly staff
8,Food was average but customer support was help...,food average customer support helpful
9,"Terrible experience, wrong order delivered.",terrible experience wrong order delivered

In [12]:
def sentiment(review):

    polarity = TextBlob(review).sentiment.polarity

    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df["Sentiment"] = df["Review"].apply(sentiment)

df

,Review,Clean_Review,Sentiment
0,The pizza was delicious and delivery was very ...,pizza delicious delivery fast,Positive
1,Food arrived cold and the packaging was damaged.,food arrived cold packaging damaged,Negative
2,Excellent customer service and tasty food.,excellent customer service tasty food,Positive
3,Delivery was late and food quality was poor.,delivery late food quality poor,Negative
4,The burger was amazing and fresh.,burger amazing fresh,Positive
5,Very expensive compared to the quantity served.,expensive compared quantity served,Negative
6,Packaging was good but delivery was slow.,packaging good delivery slow,Positive
7,Loved the pasta and friendly staff.,loved pasta friendly staff,Positive
8,Food was average but customer support was help...,food average customer support helpful,Negative
9,"Terrible experience, wrong order delivered.",terrible experience wrong order delivered,Negative

**Sentiment** **Classification**

In [13]:
df["Sentiment"].value_counts()

Sentiment
Positive    5
Negative    5
Name: count, dtype: int64

**Common Service Issues**

In [14]:
negative_reviews = df[df["Sentiment"]=="Negative"]

text = " ".join(negative_reviews["Clean_Review"])

words = text.split()

counter = Counter(words)

counter.most_common(10)

[('food', 3),
 ('arrived', 1),
 ('cold', 1),
 ('packaging', 1),
 ('damaged', 1),
 ('delivery', 1),
 ('late', 1),
 ('quality', 1),
 ('poor', 1),
 ('expensive', 1)]

In [15]:
issues = Counter(words)

for word,count in issues.most_common(10):
    print(word,"-",count)

food - 3
arrived - 1
cold - 1
packaging - 1
damaged - 1
delivery - 1
late - 1
quality - 1
poor - 1
expensive - 1

**Feedback Analysis Report**

In [16]:
total = len(df)

positive = len(df[df["Sentiment"]=="Positive"])

negative = len(df[df["Sentiment"]=="Negative"])

neutral = len(df[df["Sentiment"]=="Neutral"])

print("Restaurant Feedback Analysis Report")
print("----------------------------------")
print("Total Reviews :", total)
print("Positive Reviews :", positive)
print("Negative Reviews :", negative)
print("Neutral Reviews :", neutral)

print("\nCommon Issues")
for word,count in issues.most_common(5):
    print(word,":",count)

Restaurant Feedback Analysis Report
----------------------------------
Total Reviews : 10
Positive Reviews : 5
Negative Reviews : 5
Neutral Reviews : 0

Common Issues
food : 3
arrived : 1
cold : 1
packaging : 1
damaged : 1